#!/bin/bash
# Patch Godot HTML5 export with PWA service worker + manifest
# Run after Godot exports to builds/web/
# Auto-generates ASSETS_TO_CACHE and cache version from actual export artifacts

set -euo pipefail

BUILD_DIR="$(dirname "$0")/../builds/web"
INDEX="$BUILD_DIR/index.html"
SW="$BUILD_DIR/sw.js"
GODOT_SW="$BUILD_DIR/index.service.worker.js"
MANIFEST_SRC="$BUILD_DIR/manifest.json"

if [ ! -f "$INDEX" ]; then
    echo "ERROR: No index.html found in $BUILD_DIR"
    echo "Export from Godot first: Project -> Export -> HTML5 -> builds/web/"
    exit 1
fi

# --- Sync hand-written manifest.json to the generated file name expected by Godot ---
# Godot 4 writes index.manifest.json from export settings, but we want a single,
# project-controlled manifest.json that can have proper name/description/icons.
if [ -f "$MANIFEST_SRC" ]; then
    cp "$MANIFEST_SRC" "$BUILD_DIR/index.manifest.json"
    echo "manifest.json copied to index.manifest.json"
fi

# --- Auto-generate ASSETS_TO_CACHE from actual exported files ---
echo "Scanning export artifacts..."
ASSETS=()
while IFS= read -r -d '' f; do
    rel="${f#"$BUILD_DIR"/}"
    ASSETS+=("$rel")
done < <(find "$BUILD_DIR" -maxdepth 1 -type f \( -name "*.js" -o -name "*.wasm" -o -name "*.pck" -o -name "*.html" -o -name "*.json" -o -name "*.png" -o -name "*.webp" \) -print0 | sort -z)

if [ ${#ASSETS[@]} -eq 0 ]; then
    echo "WARNING: No export artifacts found in $BUILD_DIR"
    echo "Falling back to defaults"
    ASSETS=('index.html' 'index.js' 'index.wasm' 'index.pck' 'index.audio.worklet.js' 'index.icon.png' 'manifest.json')
fi

# Determine cache version from .pck hash
PCK_FILE=$(find "$BUILD_DIR" -maxdepth 1 -name "*.pck" -print -quit 2>/dev/null)
if [ -n "$PCK_FILE" ]; then
    CACHE_VER="swordjin-$(md5sum "$PCK_FILE" | cut -c1-8)"
else
    CACHE_VER="swordjin-$(date +%s)"
fi

# Remove files that are not referenced by the app so we don't cache stale extras.
# index.service.worker.js is installed by Godot's engine, so it must be cached.
# sw.js and index.offline.html are replaced by our own offline.html and sw.js
# is no longer registered separately.
FILTERED_ASSETS=()
for name in "${ASSETS[@]}"; do
    case "$name" in
        sw.js|index.offline.html) continue ;;
        *) FILTERED_ASSETS+=("$name") ;;
    esac
done

# Build ASSETS_TO_CACHE JSON array with relative paths, properly formatted.
# We render the entries to a temp file and then read them with proper newlines.
ASSETS_FILE=$(mktemp)
trap 'rm -f "$ASSETS_FILE"' EXIT
{
    for i in "${!FILTERED_ASSETS[@]}"; do
        if [ "$i" -gt 0 ]; then
            printf ',\n'
        fi
        printf '    "%s"' "${FILTERED_ASSETS[$i]}"
    done
} > "$ASSETS_FILE"
ASSETS_JSON=$(cat "$ASSETS_FILE")

cat > "$SW" << SWEOF
// Swordjin PWA Service Worker — auto-generated by patch_pwa.sh
const CACHE_NAME = '${CACHE_VER}';
const ASSETS_TO_CACHE = [
${ASSETS_JSON}
];

// Install — cache core assets (relative paths so app works from any base)
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(ASSETS_TO_CACHE);
    }).then(() => self.skipWaiting())
  );
});

// Activate — clean old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      );
    }).then(() => self.clients.claim())
  );
});

// Fetch — stale-while-revalidate for versioned assets, offline fallback for navigation
self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);
  const isAsset = ASSETS_TO_CACHE.some((name) => url.pathname.endsWith(name));

  event.respondWith(
    caches.match(event.request).then((cached) => {
      const fetchPromise = fetch(event.request).then((response) => {
        if (response && response.status === 200) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
        }
        return response;
      }).catch(() => cached);

      // For assets, return cached version immediately while updating in background.
      if (isAsset && cached) {
        return cached;
      }
      return fetchPromise.catch(() => {
        if (event.request.mode === 'navigate') {
          return caches.match('offline.html');
        }
        return Response.error();
      });
    })
  );
});
SWEOF

echo "Service worker written: ${#ASSETS[@]} assets cached, version ${CACHE_VER}"

# Write the generated service worker into Godot's expected file as well,
# so the engine's built-in registration installs our cache strategy.
cp "$SW" "$GODOT_SW"
echo "Service worker copied to index.service.worker.js"

# Remove any previous patch_pwa custom registration to avoid two SWs fighting.
if grep -q 'navigator.serviceWorker.register("sw.js")' "$INDEX" 2>/dev/null; then
    sed -i '/navigator.serviceWorker.register("sw.js")/,+6d' "$INDEX"
    echo "Removed legacy sw.js registration"
fi

# Replace Godot-generated index.manifest.json link with project manifest.json if present
if [ -f "$MANIFEST_SRC" ] && grep -q 'rel="manifest"' "$INDEX" 2>/dev/null; then
    sed -i 's|<link rel="manifest" href="[^"]*">|<link rel="manifest" href="manifest.json">|' "$INDEX"
    echo "Manifest link updated to manifest.json"
fi

# Add project meta tags if missing
if ! grep -q "mobile-web-app-capable" "$INDEX" 2>/dev/null; then
    sed -i 's|</head>|<meta name="theme-color" content="#c0392b">\n<meta name="mobile-web-app-capable" content="yes">\n<meta name="apple-mobile-web-app-capable" content="yes">\n<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">\n</head>|' "$INDEX"
    echo "Mobile/PWA meta tags injected"
fi

# Ensure offline.html exists
if [ ! -f "$BUILD_DIR/offline.html" ]; then
    cat > "$BUILD_DIR/offline.html" << 'OFFLINE'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Swordjin — Offline</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      background: #1a1a2e;
      color: #e0d8c8;
      font-family: -apple-system, system-ui, sans-serif;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100dvh;
      text-align: center;
      padding: 2rem;
    }
    h1 { font-size: 2rem; margin-bottom: 1rem; color: #c0392b; }
    p { font-size: 1rem; line-height: 1.6; max-width: 24em; }
    .icon { font-size: 4rem; margin-bottom: 1rem; opacity: 0.6; }
  </style>
</head>
<body>
  <div class="icon">⚔</div>
  <h1>No Connection</h1>
  <p>Swordjin needs a network connection to load. Once loaded, the game works offline.</p>
  <p style="margin-top:1rem;font-size:0.85rem;color:#887;">Try again when you have a signal.</p>
</body>
</html>
OFFLINE
    echo "offline.html created"
fi

echo ""
echo "PWA patch complete!"
echo "Files in $BUILD_DIR:"
ls -la "$BUILD_DIR"/*.{js,wasm,pck,html,json} 2>/dev/null || true
echo ""
echo "To test: python3 -m http.server 8080 --directory $BUILD_DIR"
