#!/bin/bash
# Patch Godot HTML5 export with PWA service worker + manifest
# Run after Godot exports to builds/web/
# Auto-generates ASSETS_TO_CACHE and cache version from actual export artifacts

set -e

BUILD_DIR="$(dirname "$0")/../builds/web"
INDEX="$BUILD_DIR/index.html"
SW="$BUILD_DIR/sw.js"
MANIFEST="$BUILD_DIR/manifest.json"

if [ ! -f "$INDEX" ]; then
    echo "ERROR: No index.html found in $BUILD_DIR"
    echo "Export from Godot first: Project -> Export -> HTML5 -> builds/web/"
    exit 1
fi

# --- Auto-generate ASSETS_TO_CACHE from actual exported files ---
echo "Scanning export artifacts..."
ASSETS=()
while IFS= read -r -d '' f; do
    rel="/${f#$BUILD_DIR/}"
    ASSETS+=("$rel")
done < <(find "$BUILD_DIR" -maxdepth 1 -type f \( -name "*.js" -o -name "*.wasm" -o -name "*.pck" -o -name "*.html" -o -name "*.json" -o -name "*.png" -o -name "*.webp" \) -print0 | sort -z)

if [ ${#ASSETS[@]} -eq 0 ]; then
    echo "WARNING: No export artifacts found in $BUILD_DIR"
    echo "Falling back to defaults"
    ASSETS=('/' '/index.html' '/Swordjin.js' '/Swordjin.wasm' '/Swordjin.pck' '/Swordjin.audio.worklet.js' '/manifest.json' '/icon-192.png' '/icon-512.png')
fi

# Determine project version for cache name
CACHE_VER="swordjin-v0-70"
PCK_FILE=$(find "$BUILD_DIR" -maxdepth 1 -name "*.pck" -print -quit 2>/dev/null)
if [ -n "$PCK_FILE" ]; then
    CACHE_VER="swordjin-$(md5sum "$PCK_FILE" | cut -c1-8)"
fi

# Build ASSETS_TO_CACHE JSON array
ASSETS_JSON=$(printf '  ,\n  "%s"' "${ASSETS[@]}")
ASSETS_JSON="${ASSETS_JSON:4}"  # strip leading "  ,\n  "

cat > "$SW" << SWEOF
// Swordjin PWA Service Worker — auto-generated by patch_pwa.sh
const CACHE_NAME = '${CACHE_VER}';
const ASSETS_TO_CACHE = [
${ASSETS_JSON}
];

// Install — cache core assets
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(ASSETS_TO_CACHE);
    }).then(() => self.skipWaiting())
  );
});

// Activate — clean old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      );
    }).then(() => self.clients.claim())
  );
});

// Fetch — network first, then cache, with offline fallback
self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;

  event.respondWith(
    fetch(event.request)
      .then((response) => {
        if (response.status === 200) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => {
            cache.put(event.request, clone);
          });
        }
        return response;
      })
      .catch(() => {
        return caches.match(event.request).then((r) => {
          if (r) return r;
          if (event.request.mode === 'navigate') {
            return caches.match('/offline.html');
          }
          return Response.error();
        });
      })
  );
});
SWEOF

echo "Service worker written: ${#ASSETS[@]} assets cached, version ${CACHE_VER}"

# Inject service worker registration before </body>
if grep -q "serviceWorker" "$INDEX" 2>/dev/null; then
    echo "PWA already patched — skipping injection"
else
    sed -i 's|</body>|<script>\nif ("serviceWorker" in navigator) {\n  navigator.serviceWorker.register("/sw.js").then(function(r) {\n    console.log("SW registered: " + r.scope);\n  }).catch(function(e) {\n    console.warn("SW failed: " + e);\n  });\n}\n</script>\n</body>|' "$INDEX"
    echo "Service worker registration injected"
fi

# Inject manifest link before </head>
if grep -q "manifest.json" "$INDEX" 2>/dev/null; then
    echo "Manifest already linked — skipping"
else
    sed -i 's|</head>|<link rel="manifest" href="/manifest.json">\n<meta name="theme-color" content="#c0392b">\n<meta name="mobile-web-app-capable" content="yes">\n<meta name="apple-mobile-web-app-capable" content="yes">\n<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">\n</head>|' "$INDEX"
    echo "Manifest linked"
fi

# Ensure offline.html exists
if [ ! -f "$BUILD_DIR/offline.html" ]; then
    cat > "$BUILD_DIR/offline.html" << 'OFFLINE'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Swordjin — Offline</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      background: #1a1a2e;
      color: #e0d8c8;
      font-family: -apple-system, system-ui, sans-serif;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100dvh;
      text-align: center;
      padding: 2rem;
    }
    h1 { font-size: 2rem; margin-bottom: 1rem; color: #c0392b; }
    p { font-size: 1rem; line-height: 1.6; max-width: 24em; }
    .icon { font-size: 4rem; margin-bottom: 1rem; opacity: 0.6; }
  </style>
</head>
<body>
  <div class="icon">⚔</div>
  <h1>No Connection</h1>
  <p>Swordjin needs a network connection to load. Once loaded, the game works offline.</p>
  <p style="margin-top:1rem;font-size:0.85rem;color:#887;"
     >Try again when you have a signal.</p>
</body>
</html>
OFFLINE
    echo "offline.html created"
fi

echo ""
echo "PWA patch complete!"
echo "Files in $BUILD_DIR:"
ls -la "$BUILD_DIR"/*.{js,wasm,pck,html,json} 2>/dev/null || true
echo ""
echo "To test: python3 -m http.server 8080 --directory $BUILD_DIR"