// Swordjin PWA Service Worker — auto-generated by patch_pwa.sh
const CACHE_NAME = 'swordjin-69225a3d';
const ASSETS_TO_CACHE = [
    "index.144x144.png",
    "index.180x180.png",
    "index.512x512.png",
    "index.apple-touch-icon.png",
    "index.audio.position.worklet.js",
    "index.audio.worklet.js",
    "index.html",
    "index.icon.png",
    "index.js",
    "index.manifest.json",
    "index.pck",
    "index.png",
    "index.service.worker.js",
    "index.wasm",
    "manifest.json",
    "offline.html"
];

// Install — cache core assets (relative paths so app works from any base)
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(ASSETS_TO_CACHE);
    }).then(() => self.skipWaiting())
  );
});

// Activate — clean old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      );
    }).then(() => self.clients.claim())
  );
});

// Fetch — stale-while-revalidate for versioned assets, offline fallback for navigation
self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);
  const isAsset = ASSETS_TO_CACHE.some((name) => url.pathname.endsWith(name));

  event.respondWith(
    caches.match(event.request).then((cached) => {
      const fetchPromise = fetch(event.request).then((response) => {
        if (response && response.status === 200) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
        }
        return response;
      }).catch(() => cached);

      // For assets, return cached version immediately while updating in background.
      if (isAsset && cached) {
        return cached;
      }
      return fetchPromise.catch(() => {
        if (event.request.mode === 'navigate') {
          return caches.match('offline.html');
        }
        return Response.error();
      });
    })
  );
});
