// Swordjin PWA Service Worker — auto-generated by patch_pwa.sh
const CACHE_NAME = 'swordjin-7c478370';
const ASSETS_TO_CACHE = [
  "/index.144x144.png"  ,
  "/index.180x180.png"  ,
  "/index.512x512.png"  ,
  "/index.apple-touch-icon.png"  ,
  "/index.audio.position.worklet.js"  ,
  "/index.audio.worklet.js"  ,
  "/index.html"  ,
  "/index.icon.png"  ,
  "/index.js"  ,
  "/index.manifest.json"  ,
  "/index.offline.html"  ,
  "/index.pck"  ,
  "/index.png"  ,
  "/index.service.worker.js"  ,
  "/index.wasm"  ,
  "/manifest.json"  ,
  "/offline.html"  ,
  "/sw.js"
];

// Install — cache core assets
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(ASSETS_TO_CACHE);
    }).then(() => self.skipWaiting())
  );
});

// Activate — clean old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      );
    }).then(() => self.clients.claim())
  );
});

// Fetch — network first, then cache, with offline fallback
self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;

  event.respondWith(
    fetch(event.request)
      .then((response) => {
        if (response.status === 200) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => {
            cache.put(event.request, clone);
          });
        }
        return response;
      })
      .catch(() => {
        return caches.match(event.request).then((r) => {
          if (r) return r;
          if (event.request.mode === 'navigate') {
            return caches.match('/offline.html');
          }
          return Response.error();
        });
      })
  );
});
